### ISSUE TITLE
Failed to compile -  Syntax error: Cannot read property 'map' of undefined  (useToggle.ts)

### ISSUE THREAD

**Issue by LeslieMurphy** [based-ghost/aspnet-core-react-redux-playground-template#3]
The login screen comes up briefly, then an error that useToggle.ts and useCallbackState.ts failed with the Syntax error: Cannot read property 'map' of undefined issue.

This error comes across from the server side via SignalR WebSocket opened for the GET to http://localhost:52530/hubs/users?id=YipcdXuNOH2sH2cl9w7ZYg

**Comment by based-ghost** [comment]
@LeslieMurphy - Currently I am unable to recreate using the latest version of the repository, so a few things to try:

- Make sure version of the `history` package installed is not >= `5.0.0` (the latest version must be `4.10.1` since `5.0.0` is not compatible with `redux` and/or `react-router` at the moment).
- Delete your project's local `node-modules` directory and `package-lock.json` file and run `npm install` on the `client-app` directory and then attempt to run the project - maybe refreshing the node packages might flush out some inconsistencies?
- Did you adjust any of the property settings for the `GhostUI` .NET project? May want to revert to the project's defaults and try introducing incrementally.
- **UNLIKELY**: Check the version of `node.js` you have installed on your machine and if it is a version that is a few versions or more behind, try installing a more recent version.
- **UNLIKELY**: Comment out line `import * as serviceWorker from './serviceWorker';` in the `index.tsx` file and clear your browser cache.

Let me know if you still encounter the issue

**Comment by LeslieMurphy** [comment]
Still get the same error - firing it up in Debug mode in Visual Studio.

What does this error even mean? It comes from the server connection in response to the SignalR websocket, not from within the browser itself.



Failed to compile
./src/hooks/useToggle.ts
Syntax error: Cannot read property 'map' of undefined (0:undefined)
This error occurred during the build time and cannot be dismissed.

History module is at 4.10.1
Deleted node and reinstalled all the modules
I did not change any settings that I am aware of!
Disabled the serviceworker
Node is at 12.16.2
.Net Core info:

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by based-ghost** [comment]
Ah, you're using the preview for v5.0.0 SDK - I think you may need to install the preview version of the `@microsoft/signalr` npm package: `npm install --save @microsoft/signalr@5.0.0-preview.8.20414.8`. And then maybe make sure the references in the project json point to the preview version of the SDK and packages. It has to be related to the SDK version.
`

**Comment by LeslieMurphy** [comment]
The target is .Net Core 3.1.  I tried changing it to 5.0 and that did not work.  Also tried downgrade SignalR from 1.1 to 1.04.  Still same issue.

Here is the Fiddler trace:

GET http://localhost:52530/hubs/users?id=hnRgj_aOB4Hylg4Xt0v3zA

response:
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Server: Microsoft-IIS/10.0
Sec-WebSocket-Accept: Vqq2RrQcmJE9+LI/4kg5hIKFosI=


Websocket trace:

09:41:26:8971 WSSession20.WebSocket'WebSocket #20'
MessageID:	Client.1
MessageType:	Text
PayloadString:	{"protocol":"json","version":1}
Masking:	CE-5E-63-72

09:41:26:9010 WSSession20.WebSocket'WebSocket #20'
MessageID:	Server.2
MessageType:	Text
PayloadString:	{}
Masking:	<none>

09:41:28:4764 WSSession13.WebSocket'WebSocket #13'
MessageID:	Server.1
MessageType:	Text
PayloadString:	{"type":"log-level","data":"none"}
Masking:	<none>

09:41:28:4774 WSSession13.WebSocket'WebSocket #13'
MessageID:	Server.2
MessageType:	Text
PayloadString:	{"type":"hot"}
Masking:	<none>

09:41:28:4774 WSSession13.WebSocket'WebSocket #13'
MessageID:	Server.3
MessageType:	Text
PayloadString:	{"type":"liveReload"}
Masking:	<none>

09:41:28:4774 WSSession13.WebSocket'WebSocket #13'
MessageID:	Server.4
MessageType:	Text
PayloadString:	{"type":"hash","data":"f537cde167c153f43ac1"}
Masking:	<none>

09:41:28:4774 WSSession13.WebSocket'WebSocket #13'
MessageID:	Server.5
MessageType:	Text
PayloadString:	{"type":"errors","data":["./src/hooks/useCallbackState.ts\nModule Error (from ./node_modules/eslint-loader/dist/cjs.js):\n\n  Line 0:  Parsing error: Cannot read property 'map' of undefined\n\n","./src/hooks/useToggle.ts\nModule Error (from ./node_modules/eslint-loader/dist/cjs.js):\n\n  Line 0:  Parsing error: Cannot read property 'map' of undefined\n\n"]}
Masking:	<none>

**Comment by based-ghost** [comment]
Ya this is weird - maybe check your typescript settings in the project properties in the .NET project. Or since the error doesn't seem to be originating client-side, it could be coming from the HealthChecks.UI or Swagger nuget packages - try unhooking those in the Startup.cs file one at a time and see if it has to do with the configuration of either of those.

**Comment by LeslieMurphy** [comment]
I tried removing HealthChecks and Swagger.  Still got the same error.

**Comment by based-ghost** [comment]
@LeslieMurphy - Alright this should be fixed now, so you can go ahead and clone the latest version. It turned out to be just related to that useToggle.tsx hook file - there is literally no reason that should cause any issues, but if I had to guess it might be something with the latest version of typescript and it couldn't transpile it for some reason. Just had to remove it.

**Comment by LeslieMurphy** [comment]
I just pulled code again - still getting issue: "./src/hooks/useCallbackState.ts
Syntax error: Cannot read property 'map' of undefined (0:undefined)"

PayloadString:	{"type":"errors","data":["./src/hooks/useCallbackState.ts\nModule Error (from C:/Users/lesmu/source/repos/aspnet-core-react-redux-playground-template/GhostUI/ClientApp/node_modules/eslint-loader/dist/cjs.js):\n\n  Line 0:  Parsing error: Cannot read property 'map' of undefined\n\n"]}

I also tried changing project from "use latest version available" of TypeScript to 4.0.  Still no luck!

This is only used in the Settings.tsx. 

I changed the code from:

const [isMenuOpen, setisMenuOpen] = useCallbackState<boolean>(false);

to:

const [isMenuOpen, setisMenuOpen] = useState(false);

and ran it again.  It still failed with a typescript compile error for the code in useCallbackState.ts

I then commented out the code in useCallbackState.ts - and its up and running now!

What does useCallbackState.ts wrapper even accomplish?

**Comment by based-ghost** [comment]
That actually makes sense because if you look at the `useToggle.tsx` hook's signature for input/return type it is nearly identical to that of the `useCallbackState.tsx`. I contemplated taking that out as well, but since I didn't encounter that error i just left it in, but now that you are seeing it, it's probably a matter of time before it hits me too. I have no idea why those started doing that, I haven't been able to find any other issues out there like this and there are many similar custom hooks that function just like those two. 

But the useCallbackState was just a convienence type thing so that I could return a memoized setState function, rather than having to to wrap every `useState`'s setState function in a `useCallback` in the parent component.

I just went ahead and pulled that file too from the source code - thanks for finding this, I wouldn't have noticed as it took awhile for me to encounter the errors myself.

**Comment by LeslieMurphy** [comment]
Thanks, sounds good!   I'm guessing its something in the eslint for typescript dependency chain causing this.
